import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/mentorscommunitygeneral">MentorsCommunitygeneral</Link>
        </li>
        <li>
          <Link to="/landingpagehomeloading">Landingpagehomeloading</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/talenthome">Talenthome</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/interview">Interview</Link>
        </li>
        <li>
          <Link to="/settingswalletbenefits">SettingsWalletbenefits</Link>
        </li>
        <li>
          <Link to="/mentorscommunityindividuall">
            MentorsCommunityIndividuall
          </Link>
        </li>
        <li>
          <Link to="/aboutus1">Aboutus1</Link>
        </li>
        <li>
          <Link to="/desktop5">Desktop5</Link>
        </li>
        <li>
          <Link to="/mentorssetting">Mentorssetting</Link>
        </li>
        <li>
          <Link to="/settingsupdateaccount">Settingsupdateaccount</Link>
        </li>
        <li>
          <Link to="/recruitersettingspasswordreset">
            RecruiterSettingspasswordreset
          </Link>
        </li>
        <li>
          <Link to="/recruitersettings">RecruiterSettings</Link>
        </li>
        <li>
          <Link to="/desktop2">Desktop2</Link>
        </li>
        <li>
          <Link to="/frame34308">Frame34308</Link>
        </li>
        <li>
          <Link to="/mentors">Mentors</Link>
        </li>
        <li>
          <Link to="/test">Test</Link>
        </li>
        <li>
          <Link to="/settingschangepassword">SettingsChangepassword</Link>
        </li>
        <li>
          <Link to="/desktop3">Desktop3</Link>
        </li>
        <li>
          <Link to="/desktop4">Desktop4</Link>
        </li>
        <li>
          <Link to="/landingpage">Landingpage</Link>
        </li>
        <li>
          <Link to="/landingpagehome">Landingpagehome</Link>
        </li>
        <li>
          <Link to="/landingpage1">Landingpage1</Link>
        </li>
        <li>
          <Link to="/mentorshome">Mentorshome</Link>
        </li>
        <li>
          <Link to="/signinpage">Signinpage</Link>
        </li>
        <li>
          <Link to="/resume">Resume</Link>
        </li>
        <li>
          <Link to="/signuppage">Signuppage</Link>
        </li>
        <li>
          <Link to="/settingswallet">SettingsWallet</Link>
        </li>
        <li>
          <Link to="/talenthomejobs">Talenthomejobs</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/recruiterhome">Recruiterhome</Link>
        </li>
        <li>
          <Link to="/mentorstask">Mentorstask</Link>
        </li>
        <li>
          <Link to="/community">Community</Link>
        </li>
        <li>
          <Link to="/recruiterinterview">Recruiterinterview</Link>
        </li>
        <li>
          <Link to="/desktop1">Desktop1</Link>
        </li>
        <li>
          <Link to="/mentorssetting1">Mentorssetting1</Link>
        </li>
        <li>
          <Link to="/landingpage2">Landingpage2</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
